database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:3306}
  name: ${DB_NAME:lancamento_contas}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:root}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&useLegacyDatetimeCode=false
    username: ${database.username}
    password: ${database.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

security:
  chave: "4R;40TAqR2WB,&7}lU^(]CDTWf`<BK7D~*._Ld`2T9/$ZhItYW0Z]1}2eK>K0.4R;40TAqR2WB,&7}lU^(]CDTWf`<BK7D~*._Ld`2T9/$ZhItYW0Z]1}2eK>K0."
  issuer: "lancamento-contas-api"